### ISSUE TITLE
remove alpha banner

### ISSUE THREAD

**Issue by PTiagorio** [FAIR-Protocol/decentralised-inference#308]
The "Alpha version" banner is too aggressive. We should update it to be more user-friendly. We should also align the "Alpha" name with the name the rest of the ecosystem uses.

**Comment by PTiagorio** [comment]
We should ask what name we should use to maintain coherence in the ecosystem.

**Comment by l-silvestre** [comment]
we should use "early"
maybe use a badge on top of the logo (i.e:) 

![Image](https://github.com/FAIR-Protocol/decentralised-inference/assets/43357028/68c34fe9-9348-4255-9b03-29c6ca85830c)
maybe use gray as color

**Comment by l-silvestre** [comment]
Blocked waiting for new logo design
