### ISSUE TITLE
change uploads to assets on marketplace

### ISSUE THREAD

**Issue by PTiagorio** [FAIR-Protocol/decentralised-inference#333]
We should change the upload of all information to our marketplace as an asset. This way, we can transfer royalties to other persons related to a specific model. This needs changes on scripts, studio and marketplace.

**Comment by l-silvestre** [comment]
Prompts should use default license values

**Comment by l-silvestre** [comment]
Now that models and scripts are assets, update queries accordingly;
* replace app name & app version with protocol-name and protocol-version
* update version to 1
